### ISSUE TITLE
Trying to find ltcff-files at https://github.com/nathanbraun/ltcwff-files

### ISSUE THREAD

**Issue by rea725** [nathanbraun/nathanbraun-com#11]
Hi, I downloaded the Preview of Learn to Code with Fantasy Football, v7.0.  It refers to a dataset in this repo at the following location: 
https://github.com/nathanbraun/ltcwff-files

This location is returning a 404 in Github.

**Comment by nathanbraun** [comment]
Hi @rea725, it's working for me, even when I open up a browser in private/icognito mode, can you double check this and make sure you have the URL right?  Let me know if you continue to have issues.

**Comment by rea725** [comment]
Yes.  It is working!  Human error by me, it looks like.  Thanks for the quick response!
